### ISSUE TITLE
[DOCS] - Incorrect example in the docs.

### ISSUE THREAD

**Issue by Keoooo** [runwayml/sdk-node#23]
```
task = await client.imageToVideo.retrieve(taskId);

should be 

task = await this.client.tasks.retrieve(taskId);
```

<img width="758" alt="Screenshot 2024-10-09 at 6 38 39 PM" src="https://github.com/user-attachments/assets/d51a527c-9ea2-48f0-9ba9-ef88d904fea1">

NPM VERSION USED:  1.2.0
[DOCS URL ](https://docs.dev.runwayml.com/guides/quickstart/)

**Comment by mattbasta** [comment]
Hey @Keoooo, sorry for the delayed reply on this. It looks like this was already fixed. Thanks for your report!
