### ISSUE TITLE
Cant generate portrait videos. 

### ISSUE THREAD

**Issue by stebansaa** [runwayml/sdk-node#24]
Most social videos are now portrait, please consider allowing the model to generate portrait video.

**Comment by Keoooo** [comment]
you can. change the aspect ratio. 

```
  const imageToVideo = await this.runwayClient.imageToVideo.create({
        model: 'gen3a_turbo',
        duration: 5,
        ratio: aspect_ratio,  < ----   HERE
        promptImage: imgUrl,
        promptText: prompt,
      });
```
      
   
       aspect_ratio?: '16:9' | '9:16',

**Comment by mattbasta** [comment]
As @Keoooo mentioned, you'll use the `ratio` parameter here. Note that in the latest API version, you'll pass dimensions. See the docs for more: https://docs.dev.runwayml.com/api-details/versions/2024-11-06/#ratio
