### ISSUE TITLE
Unable to Generate Vertical Videos

### ISSUE THREAD

**Issue by clqkx** [runwayml/sdk-node#39]
I encountered an issue when generating videos from images via the API. The API method always returns horizontal videos (1280x768), even when vertical input data with a resolution of 768x1280 is provided.

I used images with a resolution of 768x1280 and verified that they were not incorrectly cropped before submission.

However, the resulting video is always cropped and transformed into a horizontal format (1280x768), which differs from the expected outcome.

The API should generate vertical videos (768x1280) when the input data matches the vertical aspect ratio, as stated in the documentation.

Could you confirm if the API method supports generating vertical videos? If so, are there any additional parameters or settings to consider for obtaining vertical video output?

**Comment by mattbasta** [comment]
Hey @clqkx, can you provide the code that you're using?
