### ISSUE TITLE
Question: Will the SDK open up things like zoom, pan, tilt, roll, etc.?

### ISSUE THREAD

**Issue by cmoody** [runwayml/sdk-node#60]
Question: Will the SDK open up things like zoom, pan, tilt, roll, etc.? Im currently adding language around the prompts to do get the desired effect but wasn't sure if the SDK/API would open these up. I found a site that works around these but would prefer to use the official SDK/API.

I tried using some of these params in a REST request to the API. It looked like it might have worked but was a little hard to tell. I did try roll with no success so guessing thats not there.

**Comment by mattbasta** [comment]
Hi Chase, I don't have anything to share about camera controls at the moment.
